from __future__ import annotations

from pathlib import Path

import pytest

from chzzk.mapping.category_game_candidate import (
    ChzzkCategoryGameCandidateRow,
    build_chzzk_category_game_candidate_row,
    build_sanitized_candidate_summary,
    insert_chzzk_category_game_candidate_row,
)

DDL_PATH = Path("sql/postgres/025_chzzk_category_game_candidate.sql")


def test_candidate_table_declares_candidate_only_grain_and_status_boundary() -> None:
    sql = DDL_PATH.read_text(encoding="utf-8").lower()

    assert "create table if not exists chzzk_category_game_candidate" in sql
    assert "candidate_id bigint generated by default as identity" in sql
    assert "constraint chzzk_category_game_candidate_pk primary key (candidate_id)" in sql
    assert "chzzk_category_id text not null" in sql
    assert "canonical_game_id bigint null" in sql
    assert "status text not null" in sql
    assert "status in ('candidate', 'unresolved', 'rejected')" in sql
    assert "references dim_game (canonical_game_id)" in sql


def test_candidate_table_blocks_duplicate_specific_and_unresolved_rows() -> None:
    sql = DDL_PATH.read_text(encoding="utf-8").lower()

    assert (
        "create unique index if not exists "
        "uq_chzzk_category_game_candidate_specific"
    ) in sql
    assert (
        "on chzzk_category_game_candidate (chzzk_category_id, canonical_game_id)"
        in sql
    )
    assert "where canonical_game_id is not null" in sql
    assert (
        "create unique index if not exists "
        "uq_chzzk_category_game_candidate_unresolved_category"
    ) in sql
    assert "on chzzk_category_game_candidate (chzzk_category_id)" in sql
    assert "where status = 'unresolved' and canonical_game_id is null" in sql
    assert "status = 'unresolved'\n        or canonical_game_id is not null" in sql


def test_candidate_table_does_not_extend_current_identity_or_serving_surfaces() -> None:
    sql = DDL_PATH.read_text(encoding="utf-8").lower()

    forbidden_needles = [
        "game_external_id",
        "trusted",
        "approved",
        "mapped",
        "active",
        "serving",
        "combined",
        "raw_provider_payload",
        "category_name",
        "channel_name",
        "live_title",
        "thumbnail",
    ]
    for needle in forbidden_needles:
        assert needle not in sql


def test_build_candidate_row_accepts_specific_and_category_level_unresolved() -> None:
    specific = build_chzzk_category_game_candidate_row(
        chzzk_category_id=" synthetic-category-alpha ",
        canonical_game_id=1001,
        status="candidate",
    )
    category_level = build_chzzk_category_game_candidate_row(
        chzzk_category_id="synthetic-category-beta",
        status="unresolved",
    )

    assert specific == ChzzkCategoryGameCandidateRow(
        chzzk_category_id="synthetic-category-alpha",
        canonical_game_id=1001,
        status="candidate",
    )
    assert category_level == ChzzkCategoryGameCandidateRow(
        chzzk_category_id="synthetic-category-beta",
        canonical_game_id=None,
        status="unresolved",
    )


@pytest.mark.parametrize(
    ("overrides", "error"),
    [
        ({"chzzk_category_id": " "}, "blank_chzzk_category_id"),
        ({"status": "trusted"}, "invalid_candidate_status"),
        ({"status": "approved"}, "invalid_candidate_status"),
        ({"status": "mapped"}, "invalid_candidate_status"),
        ({"canonical_game_id": 0}, "invalid_canonical_game_id"),
        ({"canonical_game_id": -1}, "invalid_canonical_game_id"),
        (
            {"status": "candidate", "canonical_game_id": None},
            "specific_candidate_requires_canonical_game_id",
        ),
        (
            {"status": "rejected", "canonical_game_id": None},
            "specific_candidate_requires_canonical_game_id",
        ),
    ],
)
def test_build_candidate_row_rejects_invalid_candidate_storage_values(
    overrides: dict[str, object],
    error: str,
) -> None:
    payload: dict[str, object] = {
        "chzzk_category_id": "synthetic-category-alpha",
        "canonical_game_id": 1001,
        "status": "candidate",
    }
    payload.update(overrides)

    with pytest.raises(ValueError, match=error):
        build_chzzk_category_game_candidate_row(
            chzzk_category_id=str(payload["chzzk_category_id"]),
            canonical_game_id=payload["canonical_game_id"],  # type: ignore[arg-type]
            status=str(payload["status"]),
        )


def test_sanitized_candidate_summary_contains_counts_without_display_values() -> None:
    rows = [
        build_chzzk_category_game_candidate_row(
            chzzk_category_id="synthetic-category-alpha",
            canonical_game_id=1001,
            status="candidate",
        ),
        build_chzzk_category_game_candidate_row(
            chzzk_category_id="synthetic-category-alpha",
            canonical_game_id=1002,
            status="rejected",
        ),
        build_chzzk_category_game_candidate_row(
            chzzk_category_id="synthetic-category-beta",
            status="unresolved",
        ),
    ]

    summary = build_sanitized_candidate_summary(rows)
    summary_text = repr(summary).lower()

    assert summary == {
        "candidate_row_count": 3,
        "category_count": 2,
        "specific_candidate_count": 2,
        "unresolved_without_game_count": 1,
        "status_counts": {
            "candidate": 1,
            "rejected": 1,
            "unresolved": 1,
        },
    }
    forbidden_needles = [
        "category name",
        "channel",
        "live title",
        "thumbnail",
        "raw",
        "credential",
    ]
    for needle in forbidden_needles:
        assert needle not in summary_text


def test_insert_candidate_row_uses_candidate_table_only() -> None:
    class FakeCursor:
        def __init__(self) -> None:
            self.calls: list[tuple[str, tuple[object, ...]]] = []

        def execute(self, sql: str, params: tuple[object, ...]) -> None:
            self.calls.append((sql, params))

        def fetchone(self) -> tuple[int]:
            return (42,)

    cursor = FakeCursor()
    row = build_chzzk_category_game_candidate_row(
        chzzk_category_id="synthetic-category-alpha",
        canonical_game_id=1001,
        status="candidate",
    )

    inserted_id = insert_chzzk_category_game_candidate_row(cursor, row=row)

    assert inserted_id == 42
    assert len(cursor.calls) == 1
    sql, params = cursor.calls[0]
    assert "insert into chzzk_category_game_candidate" in sql.lower()
    assert "game_external_id" not in sql.lower()
    assert params == ("synthetic-category-alpha", 1001, "candidate")
