-- dim_game holds the internal canonical key used across all sources.
CREATE TABLE IF NOT EXISTS dim_game (
    -- PK keeps one stable internal identifier per canonical game.
    canonical_game_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    canonical_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT dim_game_pk PRIMARY KEY (canonical_game_id)
);

-- Index supports name-based lookup without making name an upsert key.
CREATE INDEX IF NOT EXISTS idx_dim_game_canonical_name
    ON dim_game (canonical_name);
