-- chzzk_category_game_candidate stores review-only Chzzk category-to-game candidates.
CREATE TABLE IF NOT EXISTS chzzk_category_game_candidate (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chzzk_category_id TEXT NOT NULL,
    canonical_game_id BIGINT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Surrogate PK allows category-level unresolved rows without nullable key abuse.
    CONSTRAINT chzzk_category_game_candidate_pk PRIMARY KEY (candidate_id),
    CONSTRAINT chzzk_category_game_candidate_category_id_non_empty CHECK (
        LENGTH(BTRIM(chzzk_category_id)) > 0
    ),
    CONSTRAINT chzzk_category_game_candidate_status_candidate_only CHECK (
        status IN ('candidate', 'unresolved', 'rejected')
    ),
    CONSTRAINT chzzk_category_game_candidate_specific_status_shape CHECK (
        status = 'unresolved'
        OR canonical_game_id IS NOT NULL
    ),
    CONSTRAINT chzzk_category_game_candidate_canonical_game_fk
        FOREIGN KEY (canonical_game_id)
        REFERENCES dim_game (canonical_game_id)
);

-- Blocks duplicate specific category-to-game review candidates.
CREATE UNIQUE INDEX IF NOT EXISTS uq_chzzk_category_game_candidate_specific
    ON chzzk_category_game_candidate (chzzk_category_id, canonical_game_id)
    WHERE canonical_game_id IS NOT NULL;

-- Blocks duplicate category-level unresolved rows with no game candidate.
CREATE UNIQUE INDEX IF NOT EXISTS uq_chzzk_category_game_candidate_unresolved_category
    ON chzzk_category_game_candidate (chzzk_category_id)
    WHERE status = 'unresolved' AND canonical_game_id IS NULL;

-- Supports review-state scans without changing current source views.
CREATE INDEX IF NOT EXISTS idx_chzzk_category_game_candidate_status
    ON chzzk_category_game_candidate (status, updated_at DESC);
